//
// Created by toramisu on 2015/7/13.
//
#pragma once
#ifndef LINANIL_THEME_HPP
#define LINANIL_THEME_HPP

#endif //LINANIL_THEME_HPP
#ifndef SEQTRUAN_THEME_H
#define SEQTRUAN_THEME_H

#endif //SEQTRUAN_THEME_H
#define TIMELINE_HEIGHT  280
#define TIMELINE_TRACK_PANEL_DEF_WIDTH  300
#define TIMELINE_CURSOR_EDGE_COL 0xd41616
#define TIMELINE_TRACK_FRAME_MAX_WIDTH 40
#define TIMELINE_TRACK_DEF_HEIGHT 80
#define TIMELINE_COL_BG 0x484848
const int TIMELINE_DRAG_WIDTH = 5;
#define TIMELINE_HANDLE_BUTTON_WIDTH  80;//头按钮加上为按钮的宽度


#define THEME_COLOR_TITLEBAR_BOTTOM_BORDER 250, 240, 20


#define THEME_COLOR_TRACK_THUMB_BLOCK 250, 240, 20
#define COLOR_TRACK_THUMB_BLOCK_LIGHT 150, 143, 3

#define THEME_COLOR_PANEL 47, 47, 47
#define THEME_COLOR_PANEL_BORDER_DARK 29, 29, 29
#define COLOR_PANEL_BORDER_LIGHT 54, 54, 54

#define THEME_FONT_SIZE_NORMAL 14.0f //normal font size
#define THEME_FONT_SIZE_TITLE 16.0f //normal font size
#define THEME_FONT_SIZE_MENU_ITEM 18.0f //normal font size
#define VS_MENU_RADIUS 3
#define VS_MENU_SHADOW_FEATHER 12
#define VS_MENU_SHADOW_ALPHA 0.5