//
// Created by toramisu on 2015/7/13.
//
#pragma once
#ifndef LINANIL_THEME_HPP
#define LINANIL_THEME_HPP

#endif //LINANIL_THEME_HPP
#ifndef SEQTRUAN_THEME_H
#define SEQTRUAN_THEME_H

#endif //SEQTRUAN_THEME_H
#define TIMELINE_HEIGHT  280
#define TIMELINE_TRACK_PANEL_DEF_WIDTH  300
#define TIMELINE_CURSOR_EDGE_COL 0xd41616
#define TIMELINE_TRACK_FRAME_MAX_WIDTH 40
#define TIMELINE_TRACK_DEF_HEIGHT 80
#define TIMELINE_COL_BG 0x484848
const int TIMELINE_DRAG_WIDTH = 5;
#define TIMELINE_HANDLE_BUTTON_WIDTH  80;//头按钮加上为按钮的宽度


#define COLOR_TITLEBAR_BOTTOM_BORDER 250, 240, 20


#define COLOR_TRACK_THUMB_BLOCK 250, 240, 20
#define COLOR_TRACK_THUMB_BLOCK_LIGHT 150, 143, 3

#define COLOR_PANEL_BORDER_DARK 29, 29, 29
#define COLOR_PANEL_BORDER_LIGHT 54, 54, 54